AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'NOAA Buoy Camera Data Downloader'

Parameters:
  StationIds:
    Type: String
    Default: "41001,41002,41004,41008,41009"
    Description: "Comma-separated list of NOAA buoy station IDs"
  
  BucketName:
    Type: String
    Default: "noaa-buoycams-data"
    Description: "S3 bucket name for storing images and metadata"

  TableName:
    Type: String
    Default: "noaa-buoycams-metadata"
    Description: "DynamoDB table name for storing image and meteo metadata"

Globals:
  Function:
    Timeout: 180
    MemorySize: 512
    Runtime: python3.11

Resources:
  # S3 Bucket for storing images and metadata
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: ArchiveOldData
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
              - TransitionInDays: 365
                StorageClass: DEEP_ARCHIVE

  # DynamoDB Table for metadata
  MetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: station_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: station_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  # HTTP API
  BuoyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - OPTIONS
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"

  # API Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-api"
      CodeUri: .
      Handler: api_function.lambda_handler
      Runtime: python3.11
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MetadataTable
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref DataBucket
          DYNAMODB_TABLE: !Ref MetadataTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BuoyApi
            Path: /data
            Method: GET

  # IAM Role for Lambda function
  DownloaderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                Resource:
                  # Use bucket ARN, not bucket name
                  - !Sub "${DataBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !GetAtt DataBucket.Arn
        - PolicyName: RekognitionAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rekognition:DetectText
                Resource: "*"
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:GetItem
                Resource: !GetAtt MetadataTable.Arn

  # Lambda function for downloading data
  DownloaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-downloader"
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Role: !GetAtt DownloaderRole.Arn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref DataBucket
          STATION_IDS: !Ref StationIds
          DYNAMODB_TABLE: !Ref MetadataTable
      Events:
        ScheduledDownload:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Description: "Download NOAA buoy data every 30 minutes"
            Enabled: true

  # CloudWatch Log Group
  DownloaderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${DownloaderFunction}"
      RetentionInDays: 30

Outputs:
  S3BucketName:
    Description: "Name of the S3 bucket storing the data"
    Value: !Ref DataBucket
    Export:
      Name: !Sub "${AWS::StackName}-DataBucket"

  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${BuoyApi}.execute-api.${AWS::Region}.amazonaws.com/data"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  LambdaFunctionName:
    Description: "Name of the Lambda function"
    Value: !Ref DownloaderFunction
    Export:
      Name: !Sub "${AWS::StackName}-DownloaderFunction"

  LambdaFunctionArn:
    Description: "ARN of the Lambda function"
    Value: !GetAtt DownloaderFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DownloaderFunctionArn"
